# Generated by Django 5.1.1 on 2024-09-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
