# Generated by Django 5.1.1 on 2024-09-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_journalentry_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('entries', models.ManyToManyField(to='journals.journalentry')),
            ],
        ),
    ]
