# Generated by Django 5.1.1 on 2024-09-07 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_rename_name_tag_tag_name_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='entries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journals.journalentry'),
        ),
    ]
